### ISSUE TITLE
Add cloud.terraform collection to base image

### ISSUE THREAD

**Issue by wmudge** [cloudera-labs/cldr-runner#51]

**Comment by BreakingPitt** [comment]
@wmudge I've created a pull_request that addresses this issue, please can you take a look at it and review it?

**Comment by wmudge** [comment]
This dependency is now in the base image: https://github.com/cloudera-labs/cldr-runner/blob/7bfe464fff52fb00a5da355c865c6dfac53e39c0/base/requirements.yml#L35-L36
